version: "3.9"

services:
  # Основной backend-сервис
  api:
    build:
      context: ./Profzom
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./Profzom/.env
    depends_on:
      - postgres
      - otp-bot

  # Мигратор для основного сервиса
  migrator:
    build:
      context: ./Profzom
      dockerfile: docker/migrator/Dockerfile
    volumes:
      - ./Profzom/migrations:/migrations
    env_file:
      - ./Profzom/.env
    depends_on:
      - postgres

  # PostgreSQL
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: profzoom
      POSTGRES_USER: profzoom
      POSTGRES_PASSWORD: profzoom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # OTP Telegram бот
  otp-bot:
    build:
      context: ./OTP_bot
      dockerfile: cmd/server/Dockerfile
    env_file:
      - ./OTP_bot/.env
    ports:
      - "8081:8080"

volumes:
  postgres_data:
